{
    "openapi": "3.0.1",
    "info": {
        "title": "Xerpa project-service",
        "version": "v1.1"
    },
    "servers": [
        {
            "url": "https://widgets.getxerpa.com/project-service/"
        }
    ],
    "paths": {
        "/monitoring/health-check/": {
            "get": {
                "summary": "Health check",
                "operationId": "health_check",
                "description": "",
                "parameters": [],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        },
                        "description": "Health check endpoint"
                    }
                },
                "tags": [
                    "Monitoreo"
                ]
            }
        },
		"/monitoring/sentry/": {
			"get": {
				"summary": "Sentry",
				"operationId": "sentry",
				"description": "",
				"parameters": [],
				"responses": {
					"200": {
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {}
								}
							}
						},
						"description": "Permite determinar si el servicio est√° conectado con Sentry."
					}
				},
				"tags": [
					"Monitoreo"
				]
			}
		},
        "/users/{userID}/projects/": {
            "get": {
                "summary": "Lista de metas del usuario",
                "operationId": "listar_metas",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        },
                        "description": "Lista de metas del usuario"
                    }
                },
                "tags": [
                    "Metas"
                ]
            },
            "post": {
                "summary": "Crear meta",
                "operationId": "crear_meta",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "b9e605ee-4cca-400e-99c5-ae24abca97d5"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Project"
                            },
                            "examples": {
                                "Meta sin Reglas": {
                                  "summary": "Ejemplo de meta sin reglas",
                                  "value": {
                                    "category": "7c1521e9-6d06-4c6e-9aa5-db4414afe71f",
                                    "goal_date": "2022-01-01",
                                    "total": 5000,
                                    "from_account" : "333bb09d-26ab-4fe5-8051-6619dba1eff7",
                                    "to_account" : "c80f5170-2926-4b45-af64-dfe13e24a222",
                                    "name": "mi meta prueba",
                                    "rules_list" : []
                                  }
                                },
                                "Meta con Reglas": {
                                    "summary": "Ejemplo de meta con reglas",
                                    "value": {
                                      "category": "7c1521e9-6d06-4c6e-9aa5-db4414afe71f",
                                      "goal_date": "2022-01-01",
                                      "total": 6000,
                                      "from_account" : "333bb09d-26ab-4fe5-8051-6619dba1eff7",
                                      "to_account" : "c80f5170-2926-4b45-af64-dfe13e24a222",
                                      "name": "mi meta prueba con reglas",   
                                      "rules_list" : [
                                            {
                                                "rule_type" : "01fdb81f-88ef-4f7a-bc0a-c9f66430f391",
                                                "amount": 19100.00,
                                                "status": "65729137-0844-4b28-85b5-2e81b73a948a"
                                            },
                                            {
                                                "rule_type" : "a3125075-ff44-4b8b-be29-6c73fd846872",
                                                "amount": 51000.00,
                                                "status": "94bcd197-0d33-40e4-8793-78aa42ad3220"
                                            }
                                        ]   
                                    }
                                  }
                              }                            
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                },
                "tags": [
                    "Metas"
                ]
            }
        },
        "/users/{userID}/projects/{projectID}/": {
            "get": {
                "summary": "Detalle de la meta",
                "operationId": "detalle_meta",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "1b18e880-4d56-4f33-82e3-79937477f008"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        },
                        "description": "Detalle de la meta"
                    }
                },
                "tags": [
                    "Metas"
                ]
            },
            "patch": {
                "summary": "Actualizar meta. Forma 1",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "3cb17971-e530-4070-b37f-c7b164699285"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Project"
                            },
                            "examples": {
                                "Actualizar total": {
                                  "summary": "Ejemplo actualizar total",
                                  "value": {
                                    "total": 5000
                                  }
                                },
                                "Actualizar nombre": {
                                    "summary": "Ejemplo actualizar nombre",
                                    "value": {
                                      "name": "Meta actualizada"
                                    }
                                }                                
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Updated"
                    }
                },
                "tags": [
                    "Metas"
                ]
            },
            "put": {
                "summary": "Actualizar meta. Forma 2",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "1b18e880-4d56-4f33-82e3-79937477f008"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Project"
                            },
                            "examples": {
                                "Actualizar total": {
                                  "summary": "Ejemplo actualizar total",
                                  "value": {
                                        "category": "7c1521e9-6d06-4c6e-9aa5-db4414afe71f",
                                        "goal_date": "2023-02-01",
                                        "name": "Meta actualizada",
                                        "total": 7000
                                  }
                                },
                                "Actualizar nombre": {
                                    "summary": "Ejemplo actualizar nombre",
                                    "value": {
                                        "category": "7c1521e9-6d06-4c6e-9aa5-db4414afe71f",
                                        "goal_date": "2023-02-01",
                                        "name": "Meta actualizada"
                                    }
                                }                                
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Updated"
                    }
                },
                "tags": [
                    "Metas"
                ]
            }                        
        },
        "/users/{userID}/projects/{projectID}/rules/": {
            "get": {
                "summary": "Listar las reglas de la meta",
                "operationId": "listar_reglas",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "3cb17971-e530-4070-b37f-c7b164699295"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        },
                        "description": "Lista de reglas"
                    }
                },
                "tags": [
                    "Reglas"
                ]
            },
            "post": {
                "summary": "Crear regla",
                "operationId": "crear_regla",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "3cb17971-e530-4070-b37f-c7b164699295"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Rule"
                            },
                            "examples": {
                                "Regla pasion futbolera": {
                                  "summary": "Ejemplo de regla pasion futbolera",
                                  "value": {                                    
                                    "rule_type" : "a3125075-ff44-4b8b-be29-6c73fd846872",
                                    "amount": 6600.00,
                                    "sport_team": "ed560855-40f8-4281-b3f5-6a82e30899fb",
                                    "sport_conditions": "J"                                    
                                  }
                                }
                            }                            
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                },
                "tags": [
                    "Reglas"
                ]
            }            
        },
        "/users/{userID}/projects/{projectID}/rules/{ruleID}/": {
            "get": {
                "summary": "Detalle de la regla",
                "operationId": "detaile_regla",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "1b18e880-4d56-4f33-82e3-79937477f008"
                    },
                    {
                        "in": "path",
                        "name": "ruleID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la regla",
                        "example": "6e10b138-9899-43cf-8a62-d6119456aa82"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        },
                        "description": "Detalle de la regla"
                    }
                },
                "tags": [
                    "Reglas"
                ]
            },
            "patch": {
                "summary": "Actualizar regla. Forma 1.",
                "operationId": "actualizar_regla_patch",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "3cb17971-e530-4070-b37f-c7b164699285"
                    },
                    {
                        "in": "path",
                        "name": "ruleID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la regla",
                        "example": "6e10b138-9899-43cf-8a62-d6119456aa82"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Rule"
                            },
                            "examples": {
                                "Actualizar monto": {
                                  "summary": "Ejemplo actualizar monto",
                                  "value": {
                                        "amount": 9000
                                  }
                                },
                                "Actualizar estatus": {
                                    "summary": "Ejemplo actualizar estatus",
                                    "value": {
                                        "status": "65729137-0844-4b28-85b5-2e81b73a948a"
                                    }
                                }                                
                            }
                        }
                    }
                },                
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }                         
                            }
                        },
                        "description": "Actualizar regla"
                    }
                },
                "tags": [
                    "Reglas"
                ]
            },
            "put": {
                "summary": "Actualizar regla. Forma 2.",
                "operationId": "actualizar_regla_put",
                "description": "",
                "parameters": [
                    {
                        "in": "path",
                        "name": "userID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id del usuario",
                        "example": "0390a508-dba5-4344-b77f-93e1227d42f4"
                    },
                    {
                        "in": "path",
                        "name": "projectID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la meta",
                        "example": "3cb17971-e530-4070-b37f-c7b164699285"
                    },
                    {
                        "in": "path",
                        "name": "ruleID",
                        "schema": {
                            "type": "string"
                        },
                        "required": true,
                        "description": "Id de la regla",
                        "example": "6e10b138-9899-43cf-8a62-d6119456aa82"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Rule"
                            },
                            "examples": {
                                "Actualizar monto": {
                                  "summary": "Ejemplo actualizar monto, onboarding",
                                  "value": {
                                    "user": "0390a508-dba5-4344-b77f-93e1227d42f4",
                                    "project": "3cb17971-e530-4070-b37f-c7b164699295",
                                    "rule_type": "632f7dd2-4bac-4a64-86e4-72d06ca2bd65",
                                    "rule_category": "a34b4b3f-fb71-4e0b-b82e-beb94b79932e",        
                                    "amount": 11000.00
                                  }
                                }                             
                            }
                        }
                    }
                },                   
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                }                                                      
                            }
                        },
                        "description": "Actualizar regla"
                    }
                },
                "tags": [
                    "Reglas"
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "Rule": {
                "title": "Project rule",
                "type": "object",
                "properties": {
                    "rule_type": {
                        "type": "string",
                        "description": "Rule type"
                    },
                    "amount": {
                        "type": "number",
                        "description": "Project goal date"
                    },
                    "fix_salary_execution_day": {
                        "type": "number",
                        "description": "Execution day for salary rule"
                    },
                    "execution_frequency": {
                        "type": "string",
                        "description": "Execution day for fixed amount rule"
                    },
                    "sport_team": {
                        "type": "string",
                        "description": "Sport team for sports rule"
                    },
                    "sport_conditions": {
                        "type": "string",
                        "description": "Configuration for sports rule"
                    },
                    "weather_city": {
                        "type": "string",
                        "description": "City for weather rule"
                    },
                    "temperature": {
                        "type": "string",
                        "description": "Configuration for weather rule"
                    }
                },
                "required": [
                    "rule_type",
                    "amount"
                ]
            },
            "Project": {
                "title": "User project",
                "type": "object",
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "Project category"
                    },
                    "name": {
                        "type": "string",
                        "description": "Project name"
                    },
                    "goal_date": {
                        "type": "string",
                        "description": "Project goal date"
                    },
                    "total": {
                        "type": "number",
                        "description": "Project total amount"
                    },
                    "from_account": {
                        "type": "string",
                        "description": "User account"
                    },
                    "to_account": {
                        "type": "string",
                        "description": "User account"
                    },
                    "rules_list": {
                        "type": "array",
                        "$ref": "#/components/schemas/Rule"
                    }
                },
                "required": [
                    "category",
                    "name",
                    "goal_date",
                    "total"
                ]
            }
        }
    }
}
